### ISSUE TITLE
Web-C: click on a word on a fresh load does not work

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web#106]
When you have freshly loaded a readalong, if you click on a word, it does not actually play. You have to click on it a second time before it actually plays.

The intended behaviour is to play a word as soon as it is clicked.

**Comment by dhdaines** [comment]
As I suspected, this is due to the security model of AudioContext.  You will see warnings like this in the console:

> The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

Either clicking on a word isn't good enough for Chrome to allow the audio to be resumed, or Howler isn't resuming it correctly.  There doesn't really seem to be a way to get around this problem unless we were to handle the audio ourselves.

**Comment by roedoejet** [comment]
good find. this is too bad though.

**Comment by joanise** [comment]
Darn, but OK, let's close this issue then.
