### ISSUE TITLE
 "click" play    and  word is not in view   , interface will not focus

### ISSUE THREAD

**Issue by marctessier** [ReadAlongs/Studio-Web#108]
When you load a  long page RA   , if you were at the bottom of the text and click play for example.   The interface will not focus on the first  word highlighted and also the interface starts to  jumping around till it catches up.

**Comment by joanise** [comment]
Copied from Slack. The data file is not public so I won't copy it here, but you can find it in Slack.

Marc says:

Ok, I think I see  what is happening with the "jumping" around thingy bug   with the Web-Component.
In a nut shell , this is how to reproduce it from a finished html file..  You have to patient with this example  and  "Play" that attached all the way to to the end  ( it's about 1min38 long).  (  No issues should happen on the first play :slightly_smiling_face:  ) .  Now re-click on the "Play" button.
The RA will start back at the beginning.   You won't notice any issues on that first small page, but once it hits the second "long" page, that where things will start to "jump around".
I think the issue is  that  we are  still all the way at the bottom of the page2  from that first time we  "played" it and remembers where we were and has a hard time scrolling  the page all the way up to the top on that page at  transition or something around  those lines.  I  also tried to manually scroll page 2 all the way up ,   before re-clicking  "play"   starting on page 1... it did not help ?   I had to "re-load" the page to make it work for 1 shot only.
It is also strange how it also has issues   going  "side-ways"  as well stuck in between 2 pages for a few sentence.
After a while everything does catches up  in the  test but only  because the 3rd page is small else I presume it would have danced again.

**Comment by joanise** [comment]
I've reproduced the behaviour Marc describes.

**Comment by joanise** [comment]
Oh, a quicker way to reproduce the problem:
 - scroll to page 3
 - click on either word, twice (because audio permissions...)
 - click play and wait until the end (a few seconds)
 - click play again => starts from the beginning and the bug happens when it goes to page 2, after a few seconds.

**Comment by joanise** [comment]
Argh, `scrollTo` and `scrollBy` make no sense to me. The code to scroll the word that's playing into the right location is made incredibly complicated by how those functions don't work at all in a way I understand!
